### ISSUE TITLE
Required argument `--pattern` not found even when given

### ISSUE THREAD

**Issue by Kushagra-0801** [solidiquis/erdtree#237]
I wanted to used `erd` as an `ls` replacement. Since `ls` allows globbing without flags, I thought to make an alias for erd with the `-p` already present.

I made it like this:

In config file:
```toml
[ls]
human = true
disk-usage = "logical"
long = true
level = 1
suppress-size = true
layout = "inverted"

[lsf]
human = true
disk-usage = "logical"
long = true
level = 1
suppress-size = true
layout = "inverted"
glob = true
```

and then the aliases:
```bash
alias ls='erd --config ls'
alias lsf='erd --config lsf --pattern'
```

And I tried to use it like
```bash
lsf '*'
```

I get the following error:
```
error: the following required arguments were not provided:
  --pattern <PATTERN>

Usage: -- --pattern <PATTERN> --suppress-size --glob --human --level <NUM> --disk-usage <DISK_USAGE> --long --layout <LAYOUT> [DIR]

For more information, try '--help'.
```

If I run
```bash
lsf --pattern '*'
```

I get the following error:
```
error: a value is required for '--pattern <PATTERN>' but none was supplied

For more information, try '--help'.
```

But if I run
```bash
ls --glob --pattern '*'
```

then it works.

---------------------------------------

Beyond this main issue, I have some other minor requests / questions as well.

1. How can I have globbing work for both files and directories at the same time?
2. Is there some way I can pass the pattern without quoting it? Basically, letting the shell do the globbing and have erd work like ls with arguments given.
